when using with shrinkwrap maven resolver, the archive's getContent method returns class format as "\\org\\test\\something". This causes java.lang.NoClassDefFoundError because findClassName method could not replace all slashes in class's full name.